### ISSUE TITLE
Missing type definitions

### ISSUE THREAD

**Issue by nightire** [natterstefan/editorjs-inline-tool#2]
This lib is great, however, I think it doesn't include the proper type definitions file in the published npm package, mind to double-check it?

**Comment by natterstefan** [comment]
Hi @nightire,

alright, I will check. Thanks for your message and feedback.

**Comment by natterstefan** [comment]
Hi @nightire,

I just deployed a new version (`0.4.0`) with updated types. Please test it and let me know if it works or not for you.
