### ISSUE TITLE
Remaining Something and That is Strike

### ISSUE THREAD

**Issue by akshayrathodar** [natterstefan/editorjs-inline-tool#6]
# Feature Request

Brief explanation of the feature you have in mind.

## Basic example

If you want you can include a basic code example. Omit this section if it's
not applicable.

## Motivation

Why are you suggesting this? What is the use case for it and what is the
expected outcome?

**Comment by natterstefan** [comment]
Hi @akshayrathodar,

I am not sure what you mean. Can you explain in more detail what your issue is about?, please Thanks and enjoy your day.

**Comment by dominik-zeglen** [comment]
Just guessing that @akshayrathodar tried to add strikethrough style and cought bug causing style to be stuck - there's no way to remove this style.

**Comment by natterstefan** [comment]
Did you have the same issue @dominik-zeglen? Please let me know, until then I will close this issue as it is stale.
